# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e80087c04436162ac900f5254522be912856add7771de6293776fddba16f317ecc511e9f7f4aae47daf234a7e0415d85269e8ce117dcbac5f6d5bc220626e73

test:
  secret_key_base: 779319813a03ec8b464a3f2396b570c8008a9c253ff0c63f1f53b27d29633fe054f10f349ddf6e6c13cae4151ac022d0850785cea24cfe53a0f52b43dec8ef83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
